namespace LogicPOS.UI.Components.System.Users.Permissions
{
    public class UserProfilePermissions
    {
        public const string BACKOFFICE_ACCESS = "BACKOFFICE_ACCESS";

        public static class Hardware
        {
            public const string HARDWARE_DRAWER_OPEN = "HARDWARE_DRAWER_OPEN";
        }

        public static class Tickets
        {
            public const string TICKETLIST_CHANGE_PRICE = "TICKETLIST_CHANGE_PRICE";
            public const string TICKETLIST_DELETE = "TICKETLIST_DELETE";
        }

        public static class Stocks
        {
            public const string STOCK_MERCHANDISE_ENTRY_ACCESS = "STOCK_MERCHANDISE_ENTRY_ACCESS";
            public const string BACKOFFICE_MAN_ARTICLESTOCK_MENU = "BACKOFFICE_MAN_ARTICLESTOCK_MENU";

            public static class Warehouses
            {
                public const string BACKOFFICE_MAN_WAREHOUSE_CREATE = "BACKOFFICE_MAN_WAREHOUSE_CREATE";
                public const string BACKOFFICE_MAN_WAREHOUSE_DELETE = "BACKOFFICE_MAN_WAREHOUSE_DELETE";
                public const string BACKOFFICE_MAN_WAREHOUSE_EDIT = "BACKOFFICE_MAN_WAREHOUSE_EDIT";
                public const string BACKOFFICE_MAN_WAREHOUSE_MENU = "BACKOFFICE_MAN_WAREHOUSE_MENU";
                public const string BACKOFFICE_MAN_WAREHOUSE_VIEW = "BACKOFFICE_MAN_WAREHOUSE_VIEW";
                public const string BACKOFFICE_MAN_ARTICLEWAREHOUSE_CREATE = "BACKOFFICE_MAN_ARTICLEWAREHOUSE_CREATE";
                public const string BACKOFFICE_MAN_ARTICLEWAREHOUSE_DELETE = "BACKOFFICE_MAN_ARTICLEWAREHOUSE_DELETE";
                public const string BACKOFFICE_MAN_ARTICLEWAREHOUSE_EDIT = "BACKOFFICE_MAN_ARTICLEWAREHOUSE_EDIT";
                public const string BACKOFFICE_MAN_ARTICLEWAREHOUSE_MENU = "BACKOFFICE_MAN_ARTICLEWAREHOUSE_MENU";
                public const string BACKOFFICE_MAN_ARTICLEWAREHOUSE_VIEW = "BACKOFFICE_MAN_ARTICLEWAREHOUSE_VIEW";
            }
        }

        public static class Articles
        {
            public const string BACKOFFICE_MAN_ARTICLE_CREATE = "BACKOFFICE_MAN_ARTICLE_CREATE";
            public const string BACKOFFICE_MAN_ARTICLE_DELETE = "BACKOFFICE_MAN_ARTICLE_DELETE";
            public const string BACKOFFICE_MAN_ARTICLE_EDIT = "BACKOFFICE_MAN_ARTICLE_EDIT";
            public const string BACKOFFICE_MAN_ARTICLE_MENU = "BACKOFFICE_MAN_ARTICLE_MENU";
            public const string BACKOFFICE_MAN_ARTICLE_VIEW = "BACKOFFICE_MAN_ARTICLE_VIEW";

            public static class Classes
            {
                public const string BACKOFFICE_MAN_ARTICLECLASS_CREATE = "BACKOFFICE_MAN_ARTICLECLASS_CREATE";
                public const string BACKOFFICE_MAN_ARTICLECLASS_DELETE = "BACKOFFICE_MAN_ARTICLECLASS_DELETE";
                public const string BACKOFFICE_MAN_ARTICLECLASS_EDIT = "BACKOFFICE_MAN_ARTICLECLASS_EDIT";
                public const string BACKOFFICE_MAN_ARTICLECLASS_MENU = "BACKOFFICE_MAN_ARTICLECLASS_MENU";
                public const string BACKOFFICE_MAN_ARTICLECLASS_VIEW = "BACKOFFICE_MAN_ARTICLECLASS_VIEW";
            }

            public static class Families
            {
                public const string BACKOFFICE_MAN_ARTICLEFAMILY_CREATE = "BACKOFFICE_MAN_ARTICLEFAMILY_CREATE";
                public const string BACKOFFICE_MAN_ARTICLEFAMILY_DELETE = "BACKOFFICE_MAN_ARTICLEFAMILY_DELETE";
                public const string BACKOFFICE_MAN_ARTICLEFAMILY_EDIT = "BACKOFFICE_MAN_ARTICLEFAMILY_EDIT";
                public const string BACKOFFICE_MAN_ARTICLEFAMILY_MENU = "BACKOFFICE_MAN_ARTICLEFAMILY_MENU";
                public const string BACKOFFICE_MAN_ARTICLEFAMILY_VIEW = "BACKOFFICE_MAN_ARTICLEFAMILY_VIEW";
            }

            public static class Subfamilies
            {
                public const string BACKOFFICE_MAN_ARTICLESUBFAMILY_CREATE = "BACKOFFICE_MAN_ARTICLESUBFAMILY_CREATE";
                public const string BACKOFFICE_MAN_ARTICLESUBFAMILY_DELETE = "BACKOFFICE_MAN_ARTICLESUBFAMILY_DELETE";
                public const string BACKOFFICE_MAN_ARTICLESUBFAMILY_EDIT = "BACKOFFICE_MAN_ARTICLESUBFAMILY_EDIT";
                public const string BACKOFFICE_MAN_ARTICLESUBFAMILY_MENU = "BACKOFFICE_MAN_ARTICLESUBFAMILY_MENU";
                public const string BACKOFFICE_MAN_ARTICLESUBFAMILY_VIEW = "BACKOFFICE_MAN_ARTICLESUBFAMILY_VIEW";
            }

            public static class Types
            {
                public const string BACKOFFICE_MAN_ARTICLETYPE_EDIT = "BACKOFFICE_MAN_ARTICLETYPE_EDIT";
                public const string BACKOFFICE_MAN_ARTICLETYPE_MENU = "BACKOFFICE_MAN_ARTICLETYPE_MENU";
            }

            public static class PriceTypes
            {
                public const string BACKOFFICE_MAN_CONFIGURATIONPRICETYPE_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPRICETYPE_EDIT";
                public const string BACKOFFICE_MAN_CONFIGURATIONPRICETYPE_MENU = "BACKOFFICE_MAN_CONFIGURATIONPRICETYPE_MENU";
            }

            public static class MeasurementUnits
            {
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_CREATE = "BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_CREATE";
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_DELETE = "BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_DELETE";
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_EDIT = "BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_EDIT";
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_MENU = "BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_MENU";
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_VIEW = "BACKOFFICE_MAN_CONFIGURATIONUNITMEASURE_VIEW";
            }

            public static class SizeUnits
            {
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_CREATE = "BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_CREATE";
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_DELETE = "BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_DELETE";
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_EDIT = "BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_EDIT";
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_MENU = "BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_MENU";
                public const string BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_VIEW = "BACKOFFICE_MAN_CONFIGURATIONUNITSIZE_VIEW";
            }
        }

        public static class Countries
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_CREATE = "BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_DELETE = "BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_EDIT = "BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_MENU = "BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_VIEW = "BACKOFFICE_MAN_CONFIGURATIONCOUNTRY_VIEW";
        }

        public static class Currencies
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONCURRENCY_CREATE = "BACKOFFICE_MAN_CONFIGURATIONCURRENCY_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONCURRENCY_DELETE = "BACKOFFICE_MAN_CONFIGURATIONCURRENCY_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONCURRENCY_EDIT = "BACKOFFICE_MAN_CONFIGURATIONCURRENCY_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONCURRENCY_MENU = "BACKOFFICE_MAN_CONFIGURATIONCURRENCY_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONCURRENCY_VIEW = "BACKOFFICE_MAN_CONFIGURATIONCURRENCY_VIEW";
        }

        public static class Holidays
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_CREATE = "BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_DELETE = "BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_EDIT = "BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_MENU = "BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_VIEW = "BACKOFFICE_MAN_CONFIGURATIONHOLIDAYS_VIEW";
        }

        public static class InputReaders
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_CREATE = "BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_DELETE = "BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_EDIT = "BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_MENU = "BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_VIEW = "BACKOFFICE_MAN_CONFIGURATIONINPUTREADER_VIEW";
        }

        public static class PaymentConditions
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_CREATE = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_DELETE = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_MENU = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_VIEW = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTCONDITION_VIEW";
        }

        public static class PaymentMethods
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_CREATE = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_DELETE = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_MENU = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_VIEW = "BACKOFFICE_MAN_CONFIGURATIONPAYMENTMETHOD_VIEW";
        }

        public static class Places
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACE_CREATE = "BACKOFFICE_MAN_CONFIGURATIONPLACE_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACE_DELETE = "BACKOFFICE_MAN_CONFIGURATIONPLACE_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACE_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPLACE_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACE_MENU = "BACKOFFICE_MAN_CONFIGURATIONPLACE_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACE_VIEW = "BACKOFFICE_MAN_CONFIGURATIONPLACE_VIEW";
        }

        public static class MovementTypes
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_CREATE = "BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_DELETE = "BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_MENU = "BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_VIEW = "BACKOFFICE_MAN_CONFIGURATIONPLACEMOVEMENTTYPE_VIEW";
        }

        public static class Tables
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_CREATE = "BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_DELETE = "BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_MENU = "BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_VIEW = "BACKOFFICE_MAN_CONFIGURATIONPLACETABLE_VIEW";
        }

        public static class Terminals
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACETERMINAL_DELETE = "BACKOFFICE_MAN_CONFIGURATIONPLACETERMINAL_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACETERMINAL_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPLACETERMINAL_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONPLACETERMINAL_MENU = "BACKOFFICE_MAN_CONFIGURATIONPLACETERMINAL_MENU";
        }

        public static class PoleDisplays
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_CREATE = "BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_DELETE = "BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_MENU = "BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_VIEW = "BACKOFFICE_MAN_CONFIGURATIONPOLEDISPLAY_VIEW";
        }

        public static class Printers
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERS_CREATE = "BACKOFFICE_MAN_CONFIGURATIONPRINTERS_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERS_DELETE = "BACKOFFICE_MAN_CONFIGURATIONPRINTERS_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERS_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPRINTERS_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERS_MENU = "BACKOFFICE_MAN_CONFIGURATIONPRINTERS_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERS_VIEW = "BACKOFFICE_MAN_CONFIGURATIONPRINTERS_VIEW";

            public static class Types
            {
                public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_CREATE = "BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_CREATE";
                public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_DELETE = "BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_DELETE";
                public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_EDIT";
                public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_MENU = "BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_MENU";
                public const string BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_VIEW = "BACKOFFICE_MAN_CONFIGURATIONPRINTERSTYPE_VIEW";
            }
        }

        public static class PreferenceParameters
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONPREFERENCEPARAMETER_EDIT = "BACKOFFICE_MAN_CONFIGURATIONPREFERENCEPARAMETER_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONPREFERENCEPARAMETER_VIEW = "BACKOFFICE_MAN_CONFIGURATIONPREFERENCEPARAMETER_VIEW";
            public const string BACKOFFICE_MAN_CONFIGURATIONPREFERENCEPARAMETERCOMPANY_MENU = "BACKOFFICE_MAN_CONFIGURATIONPREFERENCEPARAMETERCOMPANY_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONPREFERENCEPARAMETERSYSTEM_MENU = "BACKOFFICE_MAN_CONFIGURATIONPREFERENCEPARAMETERSYSTEM_MENU";
        }

        public static class VatRates
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONVATRATE_CREATE = "BACKOFFICE_MAN_CONFIGURATIONVATRATE_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONVATRATE_DELETE = "BACKOFFICE_MAN_CONFIGURATIONVATRATE_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONVATRATE_EDIT = "BACKOFFICE_MAN_CONFIGURATIONVATRATE_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONVATRATE_VIEW = "BACKOFFICE_MAN_CONFIGURATIONVATRATE_VIEW";
        }

        public static class VatExemptionReasons
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_CREATE = "BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_DELETE = "BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_EDIT = "BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_MENU = "BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_VIEW = "BACKOFFICE_MAN_CONFIGURATIONVATEXEMPTIONREASON_VIEW";
        }

        public static class WeighingMachines
        {
            public const string BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_CREATE = "BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_CREATE";
            public const string BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_DELETE = "BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_DELETE";
            public const string BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_EDIT = "BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_EDIT";
            public const string BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_MENU = "BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_MENU";
            public const string BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_VIEW = "BACKOFFICE_MAN_CONFIGURATIONWEIGHINGMACHINE_VIEW";
        }

        public static class Customers
        {
            public const string BACKOFFICE_MAN_CUSTOMER_CREATE = "BACKOFFICE_MAN_CUSTOMER_CREATE";
            public const string BACKOFFICE_MAN_CUSTOMER_DELETE = "BACKOFFICE_MAN_CUSTOMER_DELETE";
            public const string BACKOFFICE_MAN_CUSTOMER_EDIT = "BACKOFFICE_MAN_CUSTOMER_EDIT";
            public const string BACKOFFICE_MAN_CUSTOMER_MENU = "BACKOFFICE_MAN_CUSTOMER_MENU";
            public const string BACKOFFICE_MAN_CUSTOMER_VIEW = "BACKOFFICE_MAN_CUSTOMER_VIEW";

            public static class Types
            {
                public const string BACKOFFICE_MAN_CUSTOMERTYPE_CREATE = "BACKOFFICE_MAN_CUSTOMERTYPE_CREATE";
                public const string BACKOFFICE_MAN_CUSTOMERTYPE_DELETE = "BACKOFFICE_MAN_CUSTOMERTYPE_DELETE";
                public const string BACKOFFICE_MAN_CUSTOMERTYPE_EDIT = "BACKOFFICE_MAN_CUSTOMERTYPE_EDIT";
                public const string BACKOFFICE_MAN_CUSTOMERTYPE_MENU = "BACKOFFICE_MAN_CUSTOMERTYPE_MENU";
                public const string BACKOFFICE_MAN_CUSTOMERTYPE_VIEW = "BACKOFFICE_MAN_CUSTOMERTYPE_VIEW";
            }

            public static class DiscountGroups
            {
                public const string BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_CREATE = "BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_CREATE";
                public const string BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_DELETE = "BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_DELETE";
                public const string BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_EDIT = "BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_EDIT";
                public const string BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_MENU = "BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_MENU";
                public const string BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_VIEW = "BACKOFFICE_MAN_CUSTOMERDISCOUNTGROUP_VIEW";
            }
        }

        public static class Finance
        {
            public static class FiscalYears
            {
                public const string BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_CREATE = "BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_CREATE";
                public const string BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_DELETE = "BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_DELETE";
                public const string BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_EDIT = "BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_EDIT";
                public const string BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_MENU = "BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_MENU";
                public const string BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_VIEW = "BACKOFFICE_MAN_DOCUMENTFINANCEYEARS_VIEW";
            }

            public static class Documents
            {
                public const string FINANCE_DOCUMENT_CANCEL_DOCUMENT = "FINANCE_DOCUMENT_CANCEL_DOCUMENT";
                public const string BACKOFFICE_MAN_DOCUMENTSCURRENTACCOUNT_MENU = "BACKOFFICE_MAN_DOCUMENTSCURRENTACCOUNT_MENU";
                public const string BACKOFFICE_MAN_DOCUMENTSLISTALL_MENU = "BACKOFFICE_MAN_DOCUMENTSLISTALL_MENU";
                public const string BACKOFFICE_MAN_DOCUMENTSPAY_MENU = "BACKOFFICE_MAN_DOCUMENTSPAY_MENU";
                public const string BACKOFFICE_MAN_DOCUMENTSPAYMENTS_MENU = "BACKOFFICE_MAN_DOCUMENTSPAYMENTS_MENU";
                public const string BACKOFFICE_MAN_DOCUMENTSREPORTS_MENU = "BACKOFFICE_MAN_DOCUMENTSREPORTS_MENU";
                public const string BACKOFFICE_MAN_DOCUMENTSSHOW_MENU = "BACKOFFICE_MAN_DOCUMENTSSHOW_MENU";

                public static class Types
                {
                    public const string BACKOFFICE_MAN_DOCUMENTFINANCETYPE_CREATE = "BACKOFFICE_MAN_DOCUMENTFINANCETYPE_CREATE";
                    public const string BACKOFFICE_MAN_DOCUMENTFINANCETYPE_DELETE = "BACKOFFICE_MAN_DOCUMENTFINANCETYPE_DELETE";
                    public const string BACKOFFICE_MAN_DOCUMENTFINANCETYPE_EDIT = "BACKOFFICE_MAN_DOCUMENTFINANCETYPE_EDIT";
                    public const string BACKOFFICE_MAN_DOCUMENTFINANCETYPE_MENU = "BACKOFFICE_MAN_DOCUMENTFINANCETYPE_MENU";
                    public const string BACKOFFICE_MAN_DOCUMENTFINANCETYPE_VIEW = "BACKOFFICE_MAN_DOCUMENTFINANCETYPE_VIEW";
                }

                public static class Series
                {
                    public const string BACKOFFICE_MAN_DOCUMENTFINANCESERIES_EDIT = "BACKOFFICE_MAN_DOCUMENTFINANCESERIES_EDIT";
                    public const string BACKOFFICE_MAN_DOCUMENTFINANCESERIES_MANAGE_SERIES = "BACKOFFICE_MAN_DOCUMENTFINANCESERIES_MANAGE_SERIES";
                    public const string BACKOFFICE_MAN_DOCUMENTFINANCESERIES_VIEW = "BACKOFFICE_MAN_DOCUMENTFINANCESERIES_VIEW";

                }
            }
        }

        public static class System
        {
            public const string BACKOFFICE_MAN_SYSTEM_EXPORT_ARTICLES_MENU = "BACKOFFICE_MAN_SYSTEM_EXPORT_ARTICLES_MENU";
            public const string BACKOFFICE_MAN_SYSTEM_EXPORT_COSTUMERS_MENU = "BACKOFFICE_MAN_SYSTEM_EXPORT_COSTUMERS_MENU";
            public const string BACKOFFICE_MAN_SYSTEM_EXPORTSAFTPT_CUSTOM_MENU = "BACKOFFICE_MAN_SYSTEM_EXPORTSAFTPT_CUSTOM_MENU";
            public const string BACKOFFICE_MAN_SYSTEM_EXPORTSAFTPT_E_FATURA_MENU = "BACKOFFICE_MAN_SYSTEM_EXPORTSAFTPT_E-FATURA_MENU";
            public const string BACKOFFICE_MAN_SYSTEM_EXPORTSAFTPT_SAFTPT_MENU = "BACKOFFICE_MAN_SYSTEM_EXPORTSAFTPT_SAFTPT_MENU";
            public const string BACKOFFICE_MAN_SYSTEM_IMPORT_ARTICLES_MENU = "BACKOFFICE_MAN_SYSTEM_IMPORT_ARTICLES_MENU";
            public const string BACKOFFICE_MAN_SYSTEM_IMPORT_CUSTOMERS_MENU = "BACKOFFICE_MAN_SYSTEM_IMPORT_CUSTOMERS_MENU";

            public static class Users
            {
                public const string BACKOFFICE_MAN_USER_PRIVILEGES_APPLY = "BACKOFFICE_MAN_USER_PRIVILEGES_APPLY";

                public const string BACKOFFICE_MAN_USERCOMMISSIONGROUP_CREATE = "BACKOFFICE_MAN_USERCOMMISSIONGROUP_CREATE";
                public const string BACKOFFICE_MAN_USERCOMMISSIONGROUP_DELETE = "BACKOFFICE_MAN_USERCOMMISSIONGROUP_DELETE";
                public const string BACKOFFICE_MAN_USERCOMMISSIONGROUP_EDIT = "BACKOFFICE_MAN_USERCOMMISSIONGROUP_EDIT";
                public const string BACKOFFICE_MAN_USERCOMMISSIONGROUP_MENU = "BACKOFFICE_MAN_USERCOMMISSIONGROUP_MENU";
                public const string BACKOFFICE_MAN_USERCOMMISSIONGROUP_VIEW = "BACKOFFICE_MAN_USERCOMMISSIONGROUP_VIEW";

                public const string BACKOFFICE_MAN_USERDETAIL_CREATE = "BACKOFFICE_MAN_USERDETAIL_CREATE";
                public const string BACKOFFICE_MAN_USERDETAIL_DELETE = "BACKOFFICE_MAN_USERDETAIL_DELETE";
                public const string BACKOFFICE_MAN_USERDETAIL_EDIT = "BACKOFFICE_MAN_USERDETAIL_EDIT";
                public const string BACKOFFICE_MAN_USERDETAIL_MENU = "BACKOFFICE_MAN_USERDETAIL_MENU";
                public const string BACKOFFICE_MAN_USERDETAIL_VIEW = "BACKOFFICE_MAN_USERDETAIL_VIEW";

                public const string BACKOFFICE_MAN_USERPERMISSIONPROFILE_CREATE = "BACKOFFICE_MAN_USERPERMISSIONPROFILE_CREATE";
                public const string BACKOFFICE_MAN_USERPERMISSIONPROFILE_DELETE = "BACKOFFICE_MAN_USERPERMISSIONPROFILE_DELETE";
                public const string BACKOFFICE_MAN_USERPERMISSIONPROFILE_EDIT = "BACKOFFICE_MAN_USERPERMISSIONPROFILE_EDIT";
                public const string BACKOFFICE_MAN_USERPERMISSIONPROFILE_MENU = "BACKOFFICE_MAN_USERPERMISSIONPROFILE_MENU";
                public const string BACKOFFICE_MAN_USERPERMISSIONPROFILE_VIEW = "BACKOFFICE_MAN_USERPERMISSIONPROFILE_VIEW";
            }
        }

        public static class Reports
        {
            public const string REPORT_ACCESS = "REPORT_ACCESS";
            public const string REPORT_COMPANY_BILLING = "REPORT_COMPANY_BILLING";
            public const string REPORT_CUSTOMER_BALANCE_DETAILS = "REPORT_CUSTOMER_BALANCE_DETAILS";
            public const string REPORT_CUSTOMER_BALANCE_SUMMARY = "REPORT_CUSTOMER_BALANCE_SUMMARY";
            public const string REPORT_LIST_AUDIT_TABLE = "REPORT_LIST_AUDIT_TABLE";
            public const string REPORT_LIST_CUSTOMERS = "REPORT_LIST_CUSTOMERS";
            public const string REPORT_LIST_FAMILY_SUBFAMILY_ARTICLES = "REPORT_LIST_FAMILY_SUBFAMILY_ARTICLES";
            public const string REPORT_LIST_STOCK_ARTICLE = "REPORT_LIST_STOCK_ARTICLE";
            public const string REPORT_LIST_STOCK_GAIN = "REPORT_LIST_STOCK_GAIN";
            public const string REPORT_LIST_STOCK_MOVEMENTS = "REPORT_LIST_STOCK_MOVEMENTS";
            public const string REPORT_LIST_STOCK_SUPPLIER = "REPORT_LIST_STOCK_SUPPLIER";
            public const string REPORT_LIST_STOCK_WAREHOUSE = "REPORT_LIST_STOCK_WAREHOUSE";
            public const string REPORT_LIST_USER_COMMISSION = "REPORT_LIST_USER_COMMISSION";
            public const string REPORT_SALES_DETAIL_GROUP_PER_VAT = "REPORT_SALES_DETAIL_GROUP_PER_VAT";
            public const string REPORT_SALES_DETAIL_PER_COUNTRY = "REPORT_SALES_DETAIL_PER_COUNTRY";
            public const string REPORT_SALES_DETAIL_PER_CURRENCY = "REPORT_SALES_DETAIL_PER_CURRENCY";
            public const string REPORT_SALES_DETAIL_PER_CUSTOMER = "REPORT_SALES_DETAIL_PER_CUSTOMER";
            public const string REPORT_SALES_DETAIL_PER_DATE = "REPORT_SALES_DETAIL_PER_DATE";
            public const string REPORT_SALES_DETAIL_PER_FAMILY = "REPORT_SALES_DETAIL_PER_FAMILY";
            public const string REPORT_SALES_DETAIL_PER_FAMILY_AND_SUBFAMILY = "REPORT_SALES_DETAIL_PER_FAMILY_AND_SUBFAMILY";
            public const string REPORT_SALES_DETAIL_PER_FINANCE_DOCUMENT = "REPORT_SALES_DETAIL_PER_FINANCE_DOCUMENT";
            public const string REPORT_SALES_DETAIL_PER_PAYMENT_CONDITION = "REPORT_SALES_DETAIL_PER_PAYMENT_CONDITION";
            public const string REPORT_SALES_DETAIL_PER_PAYMENT_METHOD = "REPORT_SALES_DETAIL_PER_PAYMENT_METHOD";
            public const string REPORT_SALES_DETAIL_PER_PLACE = "REPORT_SALES_DETAIL_PER_PLACE";
            public const string REPORT_SALES_DETAIL_PER_PLACE_TABLE = "REPORT_SALES_DETAIL_PER_PLACE_TABLE";
            public const string REPORT_SALES_DETAIL_PER_TERMINAL = "REPORT_SALES_DETAIL_PER_TERMINAL";
            public const string REPORT_SALES_DETAIL_PER_USER = "REPORT_SALES_DETAIL_PER_USER";
            public const string REPORT_SALES_PER_COUNTRY = "REPORT_SALES_PER_COUNTRY";
            public const string REPORT_SALES_PER_CURRENCY = "REPORT_SALES_PER_CURRENCY";
            public const string REPORT_SALES_PER_CUSTOMER = "REPORT_SALES_PER_CUSTOMER";
            public const string REPORT_SALES_PER_DATE = "REPORT_SALES_PER_DATE";
            public const string REPORT_SALES_PER_FINANCE_DOCUMENT = "REPORT_SALES_PER_FINANCE_DOCUMENT";
            public const string REPORT_SALES_PER_PAYMENT_CONDITION = "REPORT_SALES_PER_PAYMENT_CONDITION";
            public const string REPORT_SALES_PER_PAYMENT_METHOD = "REPORT_SALES_PER_PAYMENT_METHOD";
            public const string REPORT_SALES_PER_TERMINAL = "REPORT_SALES_PER_TERMINAL";
            public const string REPORT_SALES_PER_USER = "REPORT_SALES_PER_USER";
            public const string REPORT_SALES_PER_VAT = "REPORT_SALES_PER_VAT";
            public const string REPORT_SALES_PER_VAT_BY_ARTICLE_CLASS = "REPORT_SALES_PER_VAT_BY_ARTICLE_CLASS";
            public const string REPORT_TOP_CLOSE_EMPLOYEES = "REPORT_TOP_CLOSE_EMPLOYEES";
            public const string REPORT_OCCUPATION_AVERAGE = "REPORT_OCCUPATION_AVERAGE";
            public const string REPORT_ZONE_TOTAL = "REPORT_ZONE_TOTAL";
            public const string REPORT_CLOSE_PEAK_HOUR = "REPORT_CLOSE_PEAK_HOUR";
            public const string REPORT_TOP_OFFERS = "REPORT_TOP_OFFERS";
            public const string REPORT_TOP_EMPLOYEE_RECORDS = "REPORT_TOP_EMPLOYEE_RECORDS";
            public const string REPORT_RECORD_PEAK_HOUR = "REPORT_RECORD_PEAK_HOUR";
            public const string REPORT_EMPLOYEE_MOVENTS = "REPORT_EMPLOYEE_MOVENTS";
            public const string REPORT_ACOUNT_BALANCE = "REPORT_ACOUNT_BALANCE";
            public const string REPORT_WITHHOLDING_TAX = "REPORT_WITHHOLDING_TAX";
            public const string REPORT_BALANCE_SHEET = "REPORT_BALANCE_SHEET";
            public const string REPORT_SERVICE_HOURS = "REPORT_SERVICE_HOURS";
            public const string REPORT_COURIER_DELIVER = "REPORT_COURIER_DELIVER";
            public const string REPORT_CANCELED_ARTICLES_PER_EMPLOYEE = "REPORT_CANCELED_ARTICLES_PER_EMPLOYEE";
            public const string REPORT_LIST_INVENTORY = "REPORT_LIST_INVENTORY";
            public const string REPORT_DISCOUNTS_PER_USER = "REPORT_DISCOUNTS_PER_USER";
            public const string REPORT_LIST_CONSUMPTION_PER_USER = "REPORT_LIST_CONSUMPTION_PER_USER";
            public const string REPORT_CASH_TOTAL = "REPORT_CASH_TOTAL";
            public const string REPORT_LIST_WORKSESSION = "REPORT_LIST_WORKSESSION";
            public const string REPORT_LIST_CLOSE_WORKSESSION = "REPORT_LIST_CLOSE_WORKSESSION";
        }

        public static class WorkSessions
        {
            public const string WORKSESSION_ALL = "WORKSESSION_ALL";
            public const string WORKSESSION_DAY_OPEN = "WORKSESSION_DAY_OPEN";
            public const string WORKSESSION_TERMINAL_OPEN = "WORKSESSION_TERMINAL_OPEN";
            public const string WORKSESSION_DAY_CLOSE = "WORKSESSION_DAY_CLOSE";
            public const string WORKSESSION_TERMINAL_CLOSE = "WORKSESSION_TERMINAL_CLOSE";
            public const string WORKSESSION_ORDER_MOVE = "WORKSESSION_ORDER_MOVE";
            public const string WORKSESSION_ORDER_PAYMENT = "WORKSESSION_ORDER_PAYMENT";
        }
    }
}
