//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patagames.Pdf.Net.Controls.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PdfToolStrip {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdfToolStrip() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patagames.Pdf.Net.Controls.WinForms.Properties.PdfToolStrip", typeof(PdfToolStrip).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnActualSize16Image {
            get {
                object obj = ResourceManager.GetObject("btnActualSize16Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnActualSizeImage {
            get {
                object obj = ResourceManager.GetObject("btnActualSizeImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual
        ///Size.
        /// </summary>
        internal static string btnActualSizeText {
            get {
                return ResourceManager.GetString("btnActualSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level to the page&apos;s actual size.
        /// </summary>
        internal static string btnActualSizeToolTipText {
            get {
                return ResourceManager.GetString("btnActualSizeToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnCloseDoc {
            get {
                return ResourceManager.GetString("btnCloseDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnCloseImage {
            get {
                object obj = ResourceManager.GetObject("btnCloseImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to close window.
        /// </summary>
        internal static string btnCloseToolTipText {
            get {
                return ResourceManager.GetString("btnCloseToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnCopyImage {
            get {
                object obj = ResourceManager.GetObject("btnCopyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string btnCopyText {
            get {
                return ResourceManager.GetString("btnCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selection to the clipboard.
        /// </summary>
        internal static string btnCopyToolTipText {
            get {
                return ResourceManager.GetString("btnCopyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnFirstPageImage {
            get {
                object obj = ResourceManager.GetObject("btnFirstPageImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First
        ///Page.
        /// </summary>
        internal static string btnFirstPageText {
            get {
                return ResourceManager.GetString("btnFirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the first page of the file.
        /// </summary>
        internal static string btnFirstPageToolTipText {
            get {
                return ResourceManager.GetString("btnFirstPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnFitHeight16Image {
            get {
                object obj = ResourceManager.GetObject("btnFitHeight16Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnFitHeightImage {
            get {
                object obj = ResourceManager.GetObject("btnFitHeightImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit
        ///Height.
        /// </summary>
        internal static string btnFitHeightText {
            get {
                return ResourceManager.GetString("btnFitHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level so the page height fits the window height.
        /// </summary>
        internal static string btnFitHeightToolTipText {
            get {
                return ResourceManager.GetString("btnFitHeightToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnFitPage16Image {
            get {
                object obj = ResourceManager.GetObject("btnFitPage16Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnFitPageImage {
            get {
                object obj = ResourceManager.GetObject("btnFitPageImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit
        ///Page.
        /// </summary>
        internal static string btnFitPageText {
            get {
                return ResourceManager.GetString("btnFitPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level so one full page fits in the window.
        /// </summary>
        internal static string btnFitPageToolTipText {
            get {
                return ResourceManager.GetString("btnFitPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnFitWidth16Image {
            get {
                object obj = ResourceManager.GetObject("btnFitWidth16Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnFitWidthImage {
            get {
                object obj = ResourceManager.GetObject("btnFitWidthImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit
        ///Width.
        /// </summary>
        internal static string btnFitWidthText {
            get {
                return ResourceManager.GetString("btnFitWidthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level so the page width fits the window width.
        /// </summary>
        internal static string btnFitWidthToolTipText {
            get {
                return ResourceManager.GetString("btnFitWidthToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnLastPageImage {
            get {
                object obj = ResourceManager.GetObject("btnLastPageImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last
        ///Page.
        /// </summary>
        internal static string btnLastPageText {
            get {
                return ResourceManager.GetString("btnLastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the last page of the file.
        /// </summary>
        internal static string btnLastPageToolTipText {
            get {
                return ResourceManager.GetString("btnLastPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnModeHorizontalImage {
            get {
                object obj = ResourceManager.GetObject("btnModeHorizontalImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous
        ///Horizontal.
        /// </summary>
        internal static string btnModeHorizontalText {
            get {
                return ResourceManager.GetString("btnModeHorizontalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View pages continuously with horizontal scrolling enabled.
        /// </summary>
        internal static string btnModeHorizontalToolTipText {
            get {
                return ResourceManager.GetString("btnModeHorizontalToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnModeSingleImage {
            get {
                object obj = ResourceManager.GetObject("btnModeSingleImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single
        ///Page.
        /// </summary>
        internal static string btnModeSingleText {
            get {
                return ResourceManager.GetString("btnModeSingleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View one page at time.
        /// </summary>
        internal static string btnModeSingleToolTipText {
            get {
                return ResourceManager.GetString("btnModeSingleToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnModeTilesImage {
            get {
                object obj = ResourceManager.GetObject("btnModeTilesImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous
        ///Facing.
        /// </summary>
        internal static string btnModeTilesText {
            get {
                return ResourceManager.GetString("btnModeTilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View pages side-by-side with continuous scrolling enabled.
        /// </summary>
        internal static string btnModeTilesToolTipText {
            get {
                return ResourceManager.GetString("btnModeTilesToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnModeTwoPage {
            get {
                object obj = ResourceManager.GetObject("btnModeTwoPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facing.
        /// </summary>
        internal static string btnModeTwoPageText {
            get {
                return ResourceManager.GetString("btnModeTwoPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View two pages side-by-side.
        /// </summary>
        internal static string btnModeTwoPageToolTipText {
            get {
                return ResourceManager.GetString("btnModeTwoPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnModeVerticalImage {
            get {
                object obj = ResourceManager.GetObject("btnModeVerticalImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous
        ///Vertical.
        /// </summary>
        internal static string btnModeVerticalText {
            get {
                return ResourceManager.GetString("btnModeVerticalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View pages continuously with vertical scrolling enabled.
        /// </summary>
        internal static string btnModeVerticalToolTipText {
            get {
                return ResourceManager.GetString("btnModeVerticalToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNextPageImage {
            get {
                object obj = ResourceManager.GetObject("btnNextPageImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next
        ///Page.
        /// </summary>
        internal static string btnNextPageText {
            get {
                return ResourceManager.GetString("btnNextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward one page.
        /// </summary>
        internal static string btnNextPageToolTipText {
            get {
                return ResourceManager.GetString("btnNextPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string btnOpenText {
            get {
                return ResourceManager.GetString("btnOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open a PDF file.
        /// </summary>
        internal static string btnOpenToolTipText {
            get {
                return ResourceManager.GetString("btnOpenToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnPreviousPageImage {
            get {
                object obj = ResourceManager.GetObject("btnPreviousPageImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous
        ///Page.
        /// </summary>
        internal static string btnPreviousPageText {
            get {
                return ResourceManager.GetString("btnPreviousPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back one page.
        /// </summary>
        internal static string btnPreviousPageToolTipText {
            get {
                return ResourceManager.GetString("btnPreviousPageToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnPrintImage {
            get {
                object obj = ResourceManager.GetObject("btnPrintImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string btnPrintText {
            get {
                return ResourceManager.GetString("btnPrintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to print the PDF file.
        /// </summary>
        internal static string btnPrintToolTipText {
            get {
                return ResourceManager.GetString("btnPrintToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnRotateLeftImage {
            get {
                object obj = ResourceManager.GetObject("btnRotateLeftImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate
        ///Left.
        /// </summary>
        internal static string btnRotateLeftText {
            get {
                return ResourceManager.GetString("btnRotateLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the page view 90 degrees counterclockwise.
        /// </summary>
        internal static string btnRotateLeftToolTipText {
            get {
                return ResourceManager.GetString("btnRotateLeftToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnRotateRightImage {
            get {
                object obj = ResourceManager.GetObject("btnRotateRightImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate
        ///Right.
        /// </summary>
        internal static string btnRotateRightText {
            get {
                return ResourceManager.GetString("btnRotateRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the page view 90 degrees clockwise.
        /// </summary>
        internal static string btnRotateRightToolTipText {
            get {
                return ResourceManager.GetString("btnRotateRightToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSaveDoc {
            get {
                return ResourceManager.GetString("btnSaveDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnSaveImage {
            get {
                object obj = ResourceManager.GetObject("btnSaveImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to save document.
        /// </summary>
        internal static string btnSaveToolTipText {
            get {
                return ResourceManager.GetString("btnSaveToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnSelectAllImage {
            get {
                object obj = ResourceManager.GetObject("btnSelectAllImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select
        ///All.
        /// </summary>
        internal static string btnSelectAllText {
            get {
                return ResourceManager.GetString("btnSelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the entire document.
        /// </summary>
        internal static string btnSelectAllToolTipText {
            get {
                return ResourceManager.GetString("btnSelectAllToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string btnZoomComboText {
            get {
                return ResourceManager.GetString("btnZoomComboText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the zoom level to a specific value.
        /// </summary>
        internal static string btnZoomComboToolTipText {
            get {
                return ResourceManager.GetString("btnZoomComboToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnZoomInImage {
            get {
                object obj = ResourceManager.GetObject("btnZoomInImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom
        ///In.
        /// </summary>
        internal static string btnZoomInText {
            get {
                return ResourceManager.GetString("btnZoomInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the zoom level.
        /// </summary>
        internal static string btnZoomInToolTipText {
            get {
                return ResourceManager.GetString("btnZoomInToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnZoomOutImage {
            get {
                object obj = ResourceManager.GetObject("btnZoomOutImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom
        ///Out.
        /// </summary>
        internal static string btnZoomOutText {
            get {
                return ResourceManager.GetString("btnZoomOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease the zoom level.
        /// </summary>
        internal static string btnZoomOutToolTipText {
            get {
                return ResourceManager.GetString("btnZoomOutToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        internal static string menuItemMatchCase {
            get {
                return ResourceManager.GetString("menuItemMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        internal static string menuItemMatchWholeWord {
            get {
                return ResourceManager.GetString("menuItemMatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Files (*.pdf)|*.pdf.
        /// </summary>
        internal static string OpenDialogFilter {
            get {
                return ResourceManager.GetString("OpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string searchLblnfo {
            get {
                return ResourceManager.GetString("searchLblnfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchNextDisabledImage {
            get {
                object obj = ResourceManager.GetObject("searchNextDisabledImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchNextImage {
            get {
                object obj = ResourceManager.GetObject("searchNextImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchPrevDisabledImage {
            get {
                object obj = ResourceManager.GetObject("searchPrevDisabledImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searchPrevImage {
            get {
                object obj = ResourceManager.GetObject("searchPrevImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
