//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logicpos.reports.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("logicpos.reports.Resources.Localization.Resx", typeof(Resx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount movement.
        /// </summary>
        internal static string AmountMovement {
            get {
                return ResourceManager.GetString("AmountMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmtDefault.
        /// </summary>
        internal static string AmtDefault {
            get {
                return ResourceManager.GetString("AmtDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base price.
        /// </summary>
        internal static string BasePrice {
            get {
                return ResourceManager.GetString("BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string bt_cancel {
            get {
                return ResourceManager.GetString("bt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Current Account.
        /// </summary>
        internal static string bt_CurrentAccount {
            get {
                return ResourceManager.GetString("bt_CurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C. C. Customer (detailed).
        /// </summary>
        internal static string bt_DetailsCurrentAccount {
            get {
                return ResourceManager.GetString("bt_DetailsCurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box closing.
        /// </summary>
        internal static string button_closingBox {
            get {
                return ResourceManager.GetString("button_closingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing day.
        /// </summary>
        internal static string button_closingDay {
            get {
                return ResourceManager.GetString("button_closingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string button_design {
            get {
                return ResourceManager.GetString("button_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of articles.
        /// </summary>
        internal static string button_listArticles {
            get {
                return ResourceManager.GetString("button_listArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movements by employee.
        /// </summary>
        internal static string button_movCustomers {
            get {
                return ResourceManager.GetString("button_movCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation Zone/Table.
        /// </summary>
        internal static string button_occupationPlace {
            get {
                return ResourceManager.GetString("button_occupationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top records by employee.
        /// </summary>
        internal static string button_recordsCustomer {
            get {
                return ResourceManager.GetString("button_recordsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total box.
        /// </summary>
        internal static string button_totalCash {
            get {
                return ResourceManager.GetString("button_totalCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by day.
        /// </summary>
        internal static string button_totalday {
            get {
                return ResourceManager.GetString("button_totalday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by employee.
        /// </summary>
        internal static string button_totalEmployee {
            get {
                return ResourceManager.GetString("button_totalEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by family.
        /// </summary>
        internal static string button_totalfamily {
            get {
                return ResourceManager.GetString("button_totalfamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by terminal.
        /// </summary>
        internal static string button_totalterminal {
            get {
                return ResourceManager.GetString("button_totalterminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by zone.
        /// </summary>
        internal static string button_totalzone {
            get {
                return ResourceManager.GetString("button_totalzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by zone/table.
        /// </summary>
        internal static string button_totalzonetable {
            get {
                return ResourceManager.GetString("button_totalzonetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong PIN!.
        /// </summary>
        internal static string codeErrorPin {
            get {
                return ResourceManager.GetString("codeErrorPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time payment.
        /// </summary>
        internal static string DateTimePayment {
            get {
                return ResourceManager.GetString("DateTimePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number.
        /// </summary>
        internal static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string DocumentoDate {
            get {
                return ResourceManager.GetString("DocumentoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit logicPOS.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer:.
        /// </summary>
        internal static string label_client {
            get {
                return ResourceManager.GetString("label_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee:.
        /// </summary>
        internal static string label_customer {
            get {
                return ResourceManager.GetString("label_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        internal static string label_EndDate {
            get {
                return ResourceManager.GetString("label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family:.
        /// </summary>
        internal static string label_family {
            get {
                return ResourceManager.GetString("label_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        internal static string label_StartDate {
            get {
                return ResourceManager.GetString("label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table:.
        /// </summary>
        internal static string label_table {
            get {
                return ResourceManager.GetString("label_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal:.
        /// </summary>
        internal static string label_terminal {
            get {
                return ResourceManager.GetString("label_terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement type:.
        /// </summary>
        internal static string label_typeMovement {
            get {
                return ResourceManager.GetString("label_typeMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment type:.
        /// </summary>
        internal static string label_TypePayment {
            get {
                return ResourceManager.GetString("label_TypePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone:.
        /// </summary>
        internal static string label_zone {
            get {
                return ResourceManager.GetString("label_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone:.
        /// </summary>
        internal static string label_zones {
            get {
                return ResourceManager.GetString("label_zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer:.
        /// </summary>
        internal static string lb_customer {
            get {
                return ResourceManager.GetString("lb_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data report.
        /// </summary>
        internal static string lb_reportData {
            get {
                return ResourceManager.GetString("lb_reportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment status:.
        /// </summary>
        internal static string lb_StatePay {
            get {
                return ResourceManager.GetString("lb_StatePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the reports to be able to draw!.
        /// </summary>
        internal static string Msg_Designer {
            get {
                return ResourceManager.GetString("Msg_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current search criteria do not contain data to.
        /// </summary>
        internal static string Msg_NoRecordsWereFound1 {
            get {
                return ResourceManager.GetString("Msg_NoRecordsWereFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate/display the report!.
        /// </summary>
        internal static string Msg_NoRecordsWereFound2 {
            get {
                return ResourceManager.GetString("Msg_NoRecordsWereFound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit?.
        /// </summary>
        internal static string Msg_Quit {
            get {
                return ResourceManager.GetString("Msg_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not paid.
        /// </summary>
        internal static string NotPaid {
            get {
                return ResourceManager.GetString("NotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº tables occupied.
        /// </summary>
        internal static string NTablesOccupied {
            get {
                return ResourceManager.GetString("NTablesOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price 1.
        /// </summary>
        internal static string Price1 {
            get {
                return ResourceManager.GetString("Price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price 2.
        /// </summary>
        internal static string Price2 {
            get {
                return ResourceManager.GetString("Price2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amt..
        /// </summary>
        internal static string Qnt {
            get {
                return ResourceManager.GetString("Qnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amt..
        /// </summary>
        internal static string Qt {
            get {
                return ResourceManager.GetString("Qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search again for 
        ///Terminal or Dates.
        /// </summary>
        internal static string searchTerminalDates {
            get {
                return ResourceManager.GetString("searchTerminalDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfamily.
        /// </summary>
        internal static string Subfamily {
            get {
                return ResourceManager.GetString("Subfamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string Text_Article {
            get {
                return ResourceManager.GetString("Text_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average:.
        /// </summary>
        internal static string Text_Average {
            get {
                return ResourceManager.GetString("Text_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base price.
        /// </summary>
        internal static string Text_BasePrice {
            get {
                return ResourceManager.GetString("Text_BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Text_Code {
            get {
                return ResourceManager.GetString("Text_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Text_CodeArticle {
            get {
                return ResourceManager.GetString("Text_CodeArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Text_Date {
            get {
                return ResourceManager.GetString("Text_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Text_Date_Hour {
            get {
                return ResourceManager.GetString("Text_Date_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the document.
        /// </summary>
        internal static string Text_DateDocument {
            get {
                return ResourceManager.GetString("Text_DateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Text_DateHour {
            get {
                return ResourceManager.GetString("Text_DateHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Hour paid.
        /// </summary>
        internal static string Text_DateHourPayed {
            get {
                return ResourceManager.GetString("Text_DateHourPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Text_Description {
            get {
                return ResourceManager.GetString("Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Text_Designation {
            get {
                return ResourceManager.GetString("Text_Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Text_Disc {
            get {
                return ResourceManager.GetString("Text_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string Text_From {
            get {
                return ResourceManager.GetString("Text_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        internal static string Text_MethodPayment {
            get {
                return ResourceManager.GetString("Text_MethodPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number.
        /// </summary>
        internal static string Text_NDocument {
            get {
                return ResourceManager.GetString("Text_NDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N. of tables occupied:.
        /// </summary>
        internal static string Text_NTablesOccupied {
            get {
                return ResourceManager.GetString("Text_NTablesOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Text_Payed {
            get {
                return ResourceManager.GetString("Text_Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Text_Price {
            get {
                return ResourceManager.GetString("Text_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price 1.
        /// </summary>
        internal static string Text_Price1 {
            get {
                return ResourceManager.GetString("Text_Price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price 2.
        /// </summary>
        internal static string Text_Price2 {
            get {
                return ResourceManager.GetString("Text_Price2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Text_Quant {
            get {
                return ResourceManager.GetString("Text_Quant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qt..
        /// </summary>
        internal static string Text_Quantity {
            get {
                return ResourceManager.GetString("Text_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount default.
        /// </summary>
        internal static string Text_QuantityDefault {
            get {
                return ResourceManager.GetString("Text_QuantityDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement amount.
        /// </summary>
        internal static string Text_QuantMov {
            get {
                return ResourceManager.GetString("Text_QuantMov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT rate.
        /// </summary>
        internal static string Text_RateVAT {
            get {
                return ResourceManager.GetString("Text_RateVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records:.
        /// </summary>
        internal static string Text_Records {
            get {
                return ResourceManager.GetString("Text_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Text_Report {
            get {
                return ResourceManager.GetString("Text_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing the box.
        /// </summary>
        internal static string Text_ReportTitle_ClosingBox {
            get {
                return ResourceManager.GetString("Text_ReportTitle_ClosingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing of the day.
        /// </summary>
        internal static string Text_ReportTitle_ClosingDay {
            get {
                return ResourceManager.GetString("Text_ReportTitle_ClosingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer&apos;s checking account.
        /// </summary>
        internal static string Text_ReportTitle_CurrentAccount {
            get {
                return ResourceManager.GetString("Text_ReportTitle_CurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer&apos;s checking account (details).
        /// </summary>
        internal static string Text_ReportTitle_DetailsCurrentAccount {
            get {
                return ResourceManager.GetString("Text_ReportTitle_DetailsCurrentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing of articles.
        /// </summary>
        internal static string Text_ReportTitle_ListArticles {
            get {
                return ResourceManager.GetString("Text_ReportTitle_ListArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movements by employee.
        /// </summary>
        internal static string Text_ReportTitle_MovEmployee {
            get {
                return ResourceManager.GetString("Text_ReportTitle_MovEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation zone/table.
        /// </summary>
        internal static string Text_ReportTitle_OccupationZoneTable {
            get {
                return ResourceManager.GetString("Text_ReportTitle_OccupationZoneTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock articles.
        /// </summary>
        internal static string Text_ReportTitle_StockArticles {
            get {
                return ResourceManager.GetString("Text_ReportTitle_StockArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cash.
        /// </summary>
        internal static string Text_ReportTitle_Totalcash {
            get {
                return ResourceManager.GetString("Text_ReportTitle_Totalcash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by day.
        /// </summary>
        internal static string Text_ReportTitle_TotalDay {
            get {
                return ResourceManager.GetString("Text_ReportTitle_TotalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by employee.
        /// </summary>
        internal static string Text_ReportTitle_TotalEmployee {
            get {
                return ResourceManager.GetString("Text_ReportTitle_TotalEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by family articles.
        /// </summary>
        internal static string Text_ReportTitle_TotalFamily {
            get {
                return ResourceManager.GetString("Text_ReportTitle_TotalFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by terminal.
        /// </summary>
        internal static string Text_ReportTitle_TotalTerminal {
            get {
                return ResourceManager.GetString("Text_ReportTitle_TotalTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by zones.
        /// </summary>
        internal static string Text_ReportTitle_TotalZones {
            get {
                return ResourceManager.GetString("Text_ReportTitle_TotalZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by zone/table.
        /// </summary>
        internal static string Text_ReportTitle_TotalZoneTable {
            get {
                return ResourceManager.GetString("Text_ReportTitle_TotalZoneTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top records by employee.
        /// </summary>
        internal static string Text_RepotTitle_TopRecordsEmployee {
            get {
                return ResourceManager.GetString("Text_RepotTitle_TopRecordsEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Text_Table {
            get {
                return ResourceManager.GetString("Text_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        internal static string Text_Terminal {
            get {
                return ResourceManager.GetString("Text_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string Text_To {
            get {
                return ResourceManager.GetString("Text_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (all terminals/posts ):.
        /// </summary>
        internal static string Text_TotalAll {
            get {
                return ResourceManager.GetString("Text_TotalAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by client:.
        /// </summary>
        internal static string Text_TotalClient {
            get {
                return ResourceManager.GetString("Text_TotalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total by document:.
        /// </summary>
        internal static string Text_TotalDoc {
            get {
                return ResourceManager.GetString("Text_TotalDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total excluding VAT:.
        /// </summary>
        internal static string Text_Totals_IVA {
            get {
                return ResourceManager.GetString("Text_Totals_IVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total excluding VAT.
        /// </summary>
        internal static string Text_TotalsIVA {
            get {
                return ResourceManager.GetString("Text_TotalsIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total all zones:.
        /// </summary>
        internal static string Text_TotalZones {
            get {
                return ResourceManager.GetString("Text_TotalZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Text_Type {
            get {
                return ResourceManager.GetString("Text_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type invoice.
        /// </summary>
        internal static string Text_TypeInvoice {
            get {
                return ResourceManager.GetString("Text_TypeInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type movement.
        /// </summary>
        internal static string Text_TypeMov {
            get {
                return ResourceManager.GetString("Text_TypeMov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Text_User {
            get {
                return ResourceManager.GetString("Text_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross value.
        /// </summary>
        internal static string Text_Value {
            get {
                return ResourceManager.GetString("Text_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Text_value2 {
            get {
                return ResourceManager.GetString("Text_value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        internal static string Text_Zone {
            get {
                return ResourceManager.GetString("Text_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total all zones.
        /// </summary>
        internal static string TotaAllZones {
            get {
                return ResourceManager.GetString("TotaAllZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (all terminals / stations).
        /// </summary>
        internal static string Total_allTerminal {
            get {
                return ResourceManager.GetString("Total_allTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total base.
        /// </summary>
        internal static string TotalBase {
            get {
                return ResourceManager.GetString("TotalBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total client.
        /// </summary>
        internal static string TotalClient {
            get {
                return ResourceManager.GetString("TotalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total document.
        /// </summary>
        internal static string TotalDocument {
            get {
                return ResourceManager.GetString("TotalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type movement.
        /// </summary>
        internal static string TypeMovement {
            get {
                return ResourceManager.GetString("TypeMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measurement.
        /// </summary>
        internal static string UnitMeasure {
            get {
                return ResourceManager.GetString("UnitMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT rate.
        /// </summary>
        internal static string VATRate {
            get {
                return ResourceManager.GetString("VATRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        internal static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
