namespace logicpos.Classes.Enums.Reports
{
    public enum ReportsQueryDialogMode
    {
        UNDEFINED,
        FINANCIAL,
        FINANCIAL_DETAIL,
        FINANCIAL_DETAIL_VAT,
        FINANCIAL_DETAIL_GROUP,
        SYSTEM_AUDIT,
        ARTICLE_STOCK_MOVEMENTS,
        CURRENT_ACCOUNT,
        CUSTOMER_BALANCE_DETAILS,
        CUSTOMER_BALANCE_SUMMARY,
        COMPANY_BILLING,
        FILTER_DOCUMENTS_PAGINATION,
        FILTER_DOCUMENTS_UNPAYED,
        FILTER_PAYMENT_DOCUMENTS,
        FILTER_STOCK_MOVIMENTS,
        FILTER_ARTICLE_HISTORY,
        FILTER_ARTICLE_WAREHOUSE,
        FILTER_ARTICLE_STOCK,
        FILTER_ARTICLE_STOCK_SUPPLIER,
        USER_COMMISSION,
    }
}
