namespace LogicPOS.Domain.Entities.Dtos;

public record CreateUserDto(Guid ProfileId,
                            Guid? CommissionGroupId,
                            string Name,
                            string Login,
                            string? Residence,
                            string? Locality,
                            string? ZipCode,
                            string? City,
                            string? DateOfContract,
                            string? Phone,
                            string? MobilePhone,
                            string? Email,
                            string? FiscalNumber,
                            string? Language,
                            string? AssignedSeating,
                            string? BaseConsumption,
                            string? BaseOffers,
                            string? PVPOffers,
                            string? Remarks,
                            string? ButtonImage,
                            string? Notes,
                            bool? IsDeleted,
                            bool Imported = false,
                            string? PortalPassword = null,
                            bool Need2FA = false);