namespace LogicPOS.Domain.Entities.Dtos;

public record UpdateUserDto(uint Order,
                            string Code,
                            Guid ProfileId,
                            Guid? CommissionGroupId,
                            string Name,
                            string Login,
                            string? Residence,
                            string? Locality,
                            string? ZipCpde,
                            string? City,
                            string? DateOfContract,
                            string? Phone,
                            string? MobilePhone,
                            string? Email,
                            string? FiscalNumber,
                            string? Language,
                            string? AssignedSeating,
                            string? BaseConsumption,
                            string? BaseOffers,
                            string? PVPOffers,
                            string? Remarks,
                            string? ButtonImage,
                            string? Notes,
                            bool IsDeleted);