<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LogicPOS.App</RootNamespace>
    <AssemblyName>logicpos</AssemblyName>
    <Product>logicpos</Product>
    <AssemblyTitle>logicpos</AssemblyTitle>
    <ApplicationIcon>Assets\application.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageReference Include="PDFtoImage" Version="5.4.0" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogicPOS.Core\LogicPOS.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**\*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\LogicPOS.Globalization\Localization\Resx*.resx"
                      Link="Localization\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
